### ISSUE TITLE
Docker README

### ISSUE THREAD

**Issue by noraj** [traefik/traefik-library-image#13]
The README at https://hub.docker.com/_/traefik is still using the old https://github.com/containous/traefik-library-image/blob/master/README.md instead of https://github.com/traefik/traefik-library-image/blob/master/README.md and so is still poiting to the archived https://github.com/containous/traefik-library-image.

**Comment by ldez** [comment]
The readme used by Docker is here: https://github.com/docker-library/docs/blob/master/traefik/README.md

**Comment by ldez** [comment]
I created a PR https://github.com/docker-library/docs/pull/2040

**Comment by noraj** [comment]
> The readme used by Docker is here: https://github.com/docker-library/docs/blob/master/traefik/README.md

Thank you I missed find it.

**Comment by noraj** [comment]
> I created a PR [docker-library/docs#2040](https://github.com/docker-library/docs/pull/2040)

I made https://github.com/docker-library/docs/pull/2042 to complete

**Comment by ldez** [comment]
Sorry but your PR is wrong: the most up-to-date readme content is that of the other repo.

I fixed the real missing elements https://github.com/docker-library/docs/pull/2043
