### ISSUE TITLE
missing arch ppc64le

### ISSUE THREAD

**Issue by paleozogt** [traefik/traefik-library-image#14]
While traefik has `ppc64le` releases (e.g., [here](https://github.com/traefik/traefik/releases/download/v2.5.3/traefik_v2.5.3_linux_ppc64le.tar.gz)), the official Docker image does not:
```
$ docker pull --platform linux/ppc64le library/traefik:2.5.2
2.5.2: Pulling from library/traefik
no matching manifest for linux/ppc64le in the manifest list entries
```

**Comment by gregorkistler** [comment]
Do we have any update in this regard? 🙂 I'm also quite interested into ppc64le (as well as riscv64 via #19).

**Comment by mmatur** [comment]
Fixed by https://github.com/traefik/official-images-publisher/pull/15
