### ISSUE TITLE
2.6.3 is not availiable for amd64 and s390x

### ISSUE THREAD

**Issue by fischerscode** [traefik/traefik-library-image#23]
It seems like the latest version ([2.6.3](https://hub.docker.com/layers/traefik/library/traefik/2.6.3/images/sha256-2a6e91644420e884a47301e5719349eb6a1c6c36d044c7fcfac6789aeb4b0475?context=explore)) has not been pushed for linux/amd64 and linux/s390x.
[2.6.2](https://hub.docker.com/layers/traefik/library/traefik/2.6.2/images/sha256-e2ea2ac5cf8bfb6a8e41d28915248b01e9df2a86671ec8ef2c41c38fd3285570?context=explore) is available for these platforms.

[v2.7.0-rc2](https://hub.docker.com/layers/traefik/library/traefik/v2.7.0-rc2/images/sha256-1aee5e27fbc6358f097fa0fecd790f97972a5d860b39dd15c5c0746b7cae529a?context=explore) is affected as well.

**Comment by ldez** [comment]
Hello,

The official Docker images are built by Docker itself, it's the process for official images: https://github.com/docker-library/official-images

The official Docker images of Traefik are currently under construction in the Docker build system.

The process takes time, you have to wait for a bit (several hours).

- The related PR in the Official Image repository: https://github.com/docker-library/official-images/pull/12145
- The Traefik page in the Jenkins of the Official Images: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/traefik/

Currently, their builds queue is full, so we have to wait.

**Comment by fischerscode** [comment]
Ok, thanks!
