### ISSUE TITLE
Cloudflare DNS challenge fails on newer images

### ISSUE THREAD

**Issue by damianon** [traefik/traefik-library-image#26]
When Cloudflare dnsChallenge is configured, on newer images (after 2.6.1) it fails renewing certificates with the message
`could not find the start of authority for _acme-challenge.my.domain.com`

Fortunately the internet provided me with a temporary fix, which is to revert to v2.6.1, according to this community post and now it does work again:
https://community.traefik.io/t/could-not-find-the-start-of-authority-acme-dns/13978

So there seems to be something broken in newer images

**Comment by ldez** [comment]
Hello,

`could not find the start of authority for` means that the SOA DNS query doesn't work.

It's usually a network problem.

This repository is not a place for this kind of issue.
