### ISSUE TITLE
Current windows images do not allow the use of process isolation

### ISSUE THREAD

**Issue by cardinal252** [traefik/traefik-library-image#3]
In order to use process isolation in windows, the windows base image version number must match the version number of the container of the host. If this is not the case, only hyper-v isolation is possible, which is slower.

With only having one image available on 1809 you are forcing developers to choose between hyper-v mode only for most versions of windows or to deviate and build their own container.

I have submitted a pull request to create the docker files for each major current update of windows, this would need to be merged and the build process changed to build each image.

**Comment by mloiseleur** [comment]
@cardinal252 Am I wrong to think that this issue is now solved ?

**Comment by cardinal252** [comment]
@mloiseleur I don't use traefik any more (windows or linux) it kept taking over the windows network stack entirely, so dropped it unfortunately. 

I had not seen anything to suggest it had been when I last did in c 2022. Would need to talk to developers of a product like Sitecore to see if they still use it. I would suggest though - unless windows images other than 1809 are being built, it would not be solved. Happy to continue to assist in any way I can?

**Comment by mloiseleur** [comment]
@cardinal252 Nowadays, images are built on LTS Server 2022

**Comment by cardinal252** [comment]
Truthfully - I haven't looked at process isolation compatibility for a long while on windows docker now - it would have to be chased down with a current windows based developer or from the MS documentation. I suspect just the 2 builds will limit it to hyper-v isolation mode for many use cases.

**Comment by mloiseleur** [comment]
The documentation comes with a [quite clear table](https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?source=recommendations&tabs=windows-server-2022%2Cwindows-11):
On Windows Server 2019, one need to use 2019 image for process isolation
On Windows Server 2022, one need to use 2022 image for process isolation

**Comment by mloiseleur** [comment]
Since official images only follow LTS version of Windows Server, I'll close this issue.
Feel free to re-open it if needed.
