### ISSUE TITLE
Docker sunsets the free Team Organization feature

### ISSUE THREAD

**Issue by christyjacob4** [traefik/traefik-library-image#39]
As you're aware, there has been a recent change in Docker's policy around their free Team Organization which will lead to all existing images to be deleted. More info here [https://news.ycombinator.com/item?id=35154025](https://news.ycombinator.com/item?id=35154025)

Since the `traefik` image is also [hosted on DockerHub](https://hub.docker.com/_/traefik), I wanted to check how this change will affect it and if we as consumers of the image should be concerned about it in any way or take any necessary steps.

**Comment by ldez** [comment]
The Traefik image is not related to a Docker team, because it's an official image.
Docker itself builds the Traefik Offical image.

So the Traefik image will not be impacted.

**Comment by christyjacob4** [comment]
Thanks a lot for the clarification @ldez 👍
