### ISSUE TITLE
Traefik Docker image support for ppc64le arch on Docker hub

### ISSUE THREAD

**Issue by reynold-vazp** [traefik/traefik-library-image#42]
Hi team,
We do see that Tarefik releases binaries for ppc64le arch and the Traefik dockerfile can be updated with minimal changes as per the PR(https://github.com/traefik/traefik-library-image/pull/4).
However the official multi-arch Docker image for Traefik on Docker hub doesn't support ppc64le arch, so we were wondering if we could have Traefik Docker image support for ppc64le arch on Docker hub. We can help with anything that's needed from our side.

Thanks and regards.

**Comment by ldez** [comment]
Hello,

This repository is only to handle the official Docker image.

We don't plan to distribute Traefik images in another way than the official Docker image system.

Feel free to create your own Docker image based on ppc64le.

**Comment by reynold-vazp** [comment]
> Hello,
> 
> This repository is only to handle the official Docker image.
> 
> We don't plan to distribute Traefik images in another way than the official Docker image system.
> 
> Feel free to create your own Docker image based on ppc64le.

Hey,
Yes, we were wondering if we can add ppc64le support to the official Docker image for Traefik. Please let us know if there's an issue/blocker with that.
