### ISSUE TITLE
Official docker image: `v3.0.0-beta2` is also tagged as `v3.0`, despite being pre-release (and has 2 CRIT vulns)

### ISSUE THREAD

**Issue by LeoniePhiline** [traefik/traefik-library-image#44]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Renovate-bot updated my traefik docker image tag from 2.10 to 3.

I went looking for the changelog.

### What did you see instead?

I found the changelog ending at 2.10;

upon closer inspection I found that version `v.3.0.0-beta2` is mis-tagged as `v3.0`, even though traefik 3 is not yet released.

https://hub.docker.com/_/traefik/tags?page=1&name=v3.0

![image](https://github.com/traefik/traefik/assets/22329650/6efbad47-021d-4865-a0cb-6a451b2b0921)

Note also that there are two critical vulnerabilities in Go stdlib used by traefik "v3.0":

![image](https://github.com/traefik/traefik/assets/22329650/b6d9081c-ac31-47f2-8f90-702dd3fd24c4)

### What version of Traefik are you using?

`traefik:v3.0`

### What is your environment & configuration?

Not applicable.

### If applicable, please paste the log output in DEBUG level

Not applicable.

**Comment by ldez** [comment]
Hello,

v3.0 is a reference to the latest version of a major version, it's not related to a stable version.
It's just a global reference name around v3.0 topics.

**Comment by LeoniePhiline** [comment]
Let me kindly disagree with you. This is not how semver works.

A `v3.0` tag refers to the `3.0.x` set of releases, explicitly excluding pre-releases.

In no other project have I ever encountered a major release tag being published before that major version was actually released. `beta2` ought not to be tagged as major version, without `-beta2` (`-dev`, `-pre`, `-alphaXY`, `-rcXY`) prefix. It just breaks the semver promise and wreaks havok further downstream.

**Comment by ldez** [comment]
semver doesn't talk about alias, `v3.0` is not a version but an alias to the latest version.

**Comment by mloiseleur** [comment]
Since now v3.0 has been released, I guess this issue can be closed.
Feel free to reopen it if needed.
