### ISSUE TITLE
Question: no more Traefik Web UI

### ISSUE THREAD

**Issue by Witmann** [traefik/traefik-library-image#68]
Hello, just wanted to make sur, is there no more Web UI available in the Traefik container ?

A `netstat` inside Traefik container indicates that there is nothing listening on the usual Web UI port (8080):

```
/ # netstat -tul | grep LISTEN
tcp        0      0 localhost:41381         0.0.0.0:*               LISTEN
tcp        0      0 :::http                 :::*                    LISTEN
tcp        0      0 :::https                :::*                    LISTEN
```

Thank you in advance.

**Comment by ldez** [comment]
Hello,

this repository is a technical repository only used to build the Official Docker image.

> is there no more Web UI available in the Traefik container ?

No, the Web UI is available inside the Traefik container.

Go to the [community forum](https://community.traefik.io/) if you need more help.

**Comment by Witmann** [comment]
Salut Ludovic,

Thank you for your answer, I will have a look on the forum. You are right here is only for dockerfile matters.

Cheers !
